name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: specialhua
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# 新增同步到qiniu的步骤
      - name: Upload via qshell
        env:
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_AK }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SK }}
        run: |
          # 下载七牛CLI工具
          wget http://devtools.qiniu.com/qshell-linux-x64.zip
          unzip qshell-linux-x64.zip
          # 配置账户
          ./qshell account $QINIU_ACCESS_KEY $QINIU_SECRET_KEY
          # 同步本地目录到云端
          ./qshell qupload2 --src-dir=dist --bucket=specialhua --key-prefix=snake/
