name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: specialhua
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# 新增同步到 Gitee 的步骤
      - name: Sync to Gitee
        env:
          GITEE_USER: ${{ secrets.GITEE_USERNAME }}  # 你在 Secrets 中定义的用户名
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}    # 你在 Secrets 中定义的令牌
        run: |
          # 配置 Git 身份（避免后续操作报错）
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 动态构建仓库地址（避免硬编码敏感信息）
          REPO_URL="https://${GITEE_USER}:${GITEE_TOKEN}@gitee.com/${GITEE_USER}/githubSNK.git"
          
          # 添加远程仓库并推送
          git remote add gitee $REPO_URL
          git fetch origin output
          git checkout output
          git push gitee output:output -f
