name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: specialhua
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# 新增同步到qiniu的步骤
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.QINIU_S3_ID }}
          aws-secret-access-key: ${{ secrets.QINIU_S3_KEY }}
          endpoint-url: http://s3-cn-east-1.qiniucs.com
      
      - name: Sync files
        run: |
          aws s3 sync dist/ s3://specialhua/snake/ --endpoint-url=http://s3-cn-east-1.qiniucs.com
